name: Generate Fund Charts

on:
  schedule:
    - cron: '0 1 * * *'  # 01:00 UTC = 02:00 CET
  workflow_dispatch:

permissions:
  contents: write
  packages: write  # needed for creating releases

jobs:
  run-fund-plot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip install pandas plotly

    - name: Create results folder
      run: mkdir -p results

    - name: Run fund chart generation script
      run: |
        python3 bin/interactive_fund_plot.py -t tables -r :internal: > results/fund_series_charts.stdout.html 2>/dev/null

    - name: Copy to GitHub Pages docs directory
      run: |
        mkdir -p docs
        cp results/fund_series_charts.stdout.html docs/latest_fund_series_charts.html

    - name: Commit and push if changed
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add results/fund_series_charts.stdout.html docs/latest_fund_series_charts.html

        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update fund chart HTML for $(date +%F)"
          git push
        fi

    - name: Get current date
      id: get_date
      run: echo "date_tag=fund-charts-$(date +'%F')" >> $GITHUB_OUTPUT

    - name: Create or update release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_date.outputs.date_tag }}
        name: "Fund Charts - ${{ steps.get_date.outputs.date_tag }}"
        body: "Auto-generated fund chart for ${{ steps.get_date.outputs.date_tag }}."
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload HTML as release asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_date.outputs.date_tag }}
        files: results/fund_series_charts.stdout.html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to Pages repo
      run: |
        echo "$FUND_PAGES_DEPLOY_KEY" > /tmp/deploy_key
        chmod 600 /tmp/deploy_key

        export GIT_SSH_COMMAND="ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no"
        git clone git@github.com:famantic-net/fundrider-pages.git ../fundrider-pages

        cp results/fund_series_charts.stdout.html ../fundrider-pages/docs/latest_fund_series_charts.html

        cd ../fundrider-pages
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs/latest_fund_series_charts.html

        if git diff --cached --quiet; then
          echo "No changes to publish"
        else
          git commit -m "Update chart for $(date +%F)"
          git push
        fi
      env:
        FUND_PAGES_DEPLOY_KEY: ${{ secrets.FUND_PAGES_DEPLOY_KEY }}
